-- ============================================================
-- 20260827-t-juchu-tempu.sql
-- 受注添付ファイル（PDF）機能の追加
--   1) Storage バケット juchu-tempu の作成（private / 20MB / PDFのみ）
--   2) テーブル public.t_juchu_tempu の作成
--   3) anon / authenticated への GRANT
--
-- ★GRANT は必須。CREATE TABLE だけでは PostgREST から書き込めない。
--   ステージングは public スキーマに default privileges が無く、権限が一切付かない（42501になる）。
--   本番は default privileges があるが anon には SELECT しか付かない（authenticated は全権限）。
--   どちらの環境でも、既存テーブルと同じ anon=arwd に揃えるには明示的な GRANT が必要。
-- ★RLS は有効化しない。既存テーブルはすべて relrowsecurity = false のため、
--   有効化するとポリシー0本で全アクセスが拒否され受注画面が壊れる。
--
-- 適用状況: ステージング 2026-08-27 / 本番 2026-08-27
-- ============================================================

\set ON_ERROR_STOP on

BEGIN;

-- ------------------------------------------------------------
-- 1) Storage バケット
--    private のまま運用し、アップロードは署名付きアップロードURL、
--    表示は署名付きURL（いずれも service_role が発行）で行う。
--    storage.objects は RLS有効・ポリシー0本なので、
--    anon / authenticated からの直アクセスは全拒否される（意図どおり）。
-- ------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('juchu-tempu', 'juchu-tempu', false, 20971520, ARRAY['application/pdf'])
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------
-- 2) テーブル
--    FK制約は張らない（このDBはFK 0件）。
--    採番は identity。添付は複数タブから連続でINSERTされるため、
--    他テーブルの max(id)+1 方式ではPK衝突が起きうる。
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.t_juchu_tempu (
  juchu_tempu_id integer                GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  juchu_head_id  integer                NOT NULL,
  file_nam       character varying(255) NOT NULL,
  file_pat       text                   NOT NULL,
  file_siz       bigint,
  mime_typ       character varying(100),
  mem            character varying(200),
  del_flg        integer DEFAULT 0,
  add_dat        timestamp with time zone,
  add_user       character varying(100),
  upd_dat        timestamp with time zone,
  upd_user       character varying(50)
);

COMMENT ON TABLE  public.t_juchu_tempu                IS '受注添付ファイル。受注ヘッダー単位でPDFを保持する';
COMMENT ON COLUMN public.t_juchu_tempu.file_nam       IS '原本ファイル名（日本語可）。表示用';
COMMENT ON COLUMN public.t_juchu_tempu.file_pat       IS 'Storageバケット juchu-tempu 内のオブジェクトキー（{juchu_head_id}/{uuid}.pdf）';
COMMENT ON COLUMN public.t_juchu_tempu.file_siz       IS 'バイト数';

-- ------------------------------------------------------------
-- 3) インデックス
-- ------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS t_juchu_tempu_file_pat_key
  ON public.t_juchu_tempu (file_pat);

CREATE INDEX IF NOT EXISTS t_juchu_tempu_juchu_head_id_idx
  ON public.t_juchu_tempu (juchu_head_id) WHERE del_flg = 0;

-- ------------------------------------------------------------
-- 4) 権限（★必須）
--    既存テーブルの relacl に合わせる:
--      anon          = arwd
--      authenticated = arwdDxt
-- ------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON public.t_juchu_tempu TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.t_juchu_tempu TO authenticated;

COMMIT;

-- ------------------------------------------------------------
-- 適用後の確認
-- ------------------------------------------------------------
SELECT array_to_string(relacl, ' | ') AS acl, relrowsecurity AS rls
FROM pg_class WHERE oid = 'public.t_juchu_tempu'::regclass;

SELECT id, public, file_size_limit, allowed_mime_types
FROM storage.buckets WHERE id = 'juchu-tempu';
