import { FormItemsType } from '@/app/(main)/_ui/form-box';

import { EqptsMasterDialogValues, EqptsMasterTableValues } from './types';

/* 機材マスタヘッダー */
export const eqptMHeader = [
  { key: 'name', label: '機材名' },
  { key: 'kizaiQty', label: '保有数' },
  { key: 'bumonNam', label: '部門' },
  { key: 'daibumonNam', label: '大部門' },
  { key: 'shukeibumonNam', label: '集計部門' },
  { key: 'kizaiGrpCod', label: '一式' },
  { key: 'shozokuNam', label: 'シリアル' },
  { key: 'rankAmt1', label: '価格1' },
  { key: 'rankAmt2', label: '価格2' },
  { key: 'rankAmt3', label: '価格3' },
  { key: 'rankAmt4', label: '価格4' },
  { key: 'rankAmt5', label: '価格5' },
  { key: 'mem', label: 'メモ' },
  { key: 'hidden', label: '非表示' },
];

/*  */
export const emptyEqpt: EqptsMasterDialogValues = {
  kizaiNam: '',
  sectionNum: 0,
  elNum: 0,
  delFlg: false,
  shozokuId: 0,
  bldCod: '',
  tanaCod: '',
  edaCod: '',
  kizaiGrpCod: '',
  dspOrdNum: 0,
  mem: '',
  bumonId: 0,
  shukeibumonId: 0,
  dspFlg: true,
  ctnFlg: false,
  defDatQty: 0,
  regAmt: 0,
  rankAmt1: 0,
  rankAmt2: 0,
  rankAmt3: 0,
  rankAmt4: 0,
  rankAmt5: 0,
};

/*  */
export const formItems: FormItemsType[] = [
  {
    label: '機材名',
    exsample: '例）MagicQ MQ70 Compact Console',
    constraints: '',
  },
  {
    label: '保有数',
    exsample: '',
    constraints: '数字',
  },
  {
    label: '課',
    exsample: '例）1',
    constraints: '数字',
    other: '所属無[0]、Ⅰ課[1]、Ⅱ課[2]、Ⅲ課[3]、Ⅳ課[4]、Ⅴ課[5]',
  },
  {
    label: 'EL NO.',
    exsample: '例）1',
    constraints: '数字',
  },
  {
    label: '削除フラグ',
    exsample: '',
    constraints: '選択',
  },
  {
    label: '所属',
    exsample: '',
    constraints: '',
  },
  {
    label: '棟フロアコード',
    exsample: '例）A1',
    constraints: '20文字まで',
  },
  {
    label: '棚コード',
    exsample: '例）10000',
    constraints: '20文字まで',
  },
  {
    label: '枝コード',
    exsample: '例）1',
    constraints: '20文字まで',
  },
  {
    label: '機材グループコード',
    exsample: '例）10001',
    constraints: '10文字まで',
  },
  {
    label: 'グループ内表示順',
    exsample: '例）1',
    constraints: '数字',
  },
  {
    label: 'メモ',
    exsample: '',
    constraints: '200文字まで',
  },
  {
    label: '部門',
    exsample: '例）ムービングライト',
    constraints: 'リスト選択、または、入力（100文字まで）',
  },
  {
    label: '集計部門',
    exsample: '例）照明部',
    constraints: 'リスト選択、または、入力（100文字まで）',
  },
  {
    label: '表示フラグ',
    exsample: '',
    constraints: '選択リストへの表示',
  },
  {
    label: 'コンテナフラグ',
    exsample: '',
    constraints: 'コンテナ系の場合チェック（入出庫するザル、台車など）',
  },
  {
    label: 'デフォルト日数',
    exsample: '例）1',
    constraints: '数字　出庫前の移動に必要な日数',
  },
  {
    label: '定価',
    exsample: '例）10000',
    constraints: '円貨',
  },
  {
    label: '顧客ランク価格１',
    exsample: '例）10000',
    constraints: '円貨 当該ランク価格が未入力の場合、受注伝票では定価が適用されます。',
  },
  {
    label: '顧客ランク価格2',
    exsample: '例）10000',
    constraints: '円貨 当該ランク価格が未入力の場合、受注伝票では定価が適用されます。',
  },
  {
    label: '顧客ランク価格3',
    exsample: '例）10000',
    constraints: '円貨 当該ランク価格が未入力の場合、受注伝票では定価が適用されます。',
  },
  {
    label: '顧客ランク価格4',
    exsample: '例）10000',
    constraints: '円貨 当該ランク価格が未入力の場合、受注伝票では定価が適用されます。',
  },
  {
    label: '顧客ランク価格5',
    exsample: '例）10000',
    constraints: '円貨 当該ランク価格が未入力の場合、受注伝票では定価が適用されます。',
  },
];

/** 削除データ delete data */

export const eqptMasterList: EqptsMasterTableValues[] = [
  {
    kizaiId: 1,
    kizaiNam: 'SHARPY PLUS',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1000,
    rankAmt1: 1000,
    rankAmt2: 900,
    rankAmt3: 800,
    rankAmt4: 700,
    rankAmt5: 600,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 2,
    kizaiNam: 'ROBIN T2 Profile',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1001,
    rankAmt1: 1001,
    rankAmt2: 901,
    rankAmt3: 801,
    rankAmt4: 701,
    rankAmt5: 601,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 3,
    kizaiNam: 'ROBIN Pointe_Ω',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1002,
    rankAmt1: 1002,
    rankAmt2: 902,
    rankAmt3: 802,
    rankAmt4: 702,
    rankAmt5: 602,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 4,
    kizaiNam: 'MAC Ultra Wash',
    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1003,
    rankAmt1: 1003,
    rankAmt2: 903,
    rankAmt3: 803,
    rankAmt4: 703,
    rankAmt5: 603,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 5,
    kizaiNam: 'SHARPY PLUS',
    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1004,
    rankAmt1: 1004,
    rankAmt2: 904,
    rankAmt3: 804,
    rankAmt4: 704,
    rankAmt5: 604,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 6,
    kizaiNam: 'ROBIN T3 Profile',
    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1005,
    rankAmt1: 1005,
    rankAmt2: 905,
    rankAmt3: 805,
    rankAmt4: 705,
    rankAmt5: 605,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 7,
    kizaiNam: 'ROBIN Pointe_Ω',
    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1006,
    rankAmt1: 1006,
    rankAmt2: 906,
    rankAmt3: 806,
    rankAmt4: 706,
    rankAmt5: 606,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 8,
    kizaiNam: 'MAC Ultra Wash',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1007,
    rankAmt1: 1007,
    rankAmt2: 907,
    rankAmt3: 807,
    rankAmt4: 707,
    rankAmt5: 607,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 9,
    kizaiNam: 'SHARPY PLUS',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1008,
    rankAmt1: 1008,
    rankAmt2: 908,
    rankAmt3: 808,
    rankAmt4: 708,
    rankAmt5: 608,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 10,
    kizaiNam: 'ROBIN T4 Profile',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1009,
    rankAmt1: 1009,
    rankAmt2: 909,
    rankAmt3: 809,
    rankAmt4: 709,
    rankAmt5: 609,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 11,
    kizaiNam: 'ROBIN Pointe_Ω',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1010,
    rankAmt1: 1010,
    rankAmt2: 910,
    rankAmt3: 810,
    rankAmt4: 710,
    rankAmt5: 610,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 12,
    kizaiNam: 'MAC Ultra Wash',

    shozokuNam: '',
    regAmt: 1011,
    rankAmt1: 1011,
    rankAmt2: 911,
    rankAmt3: 811,
    rankAmt4: 711,
    rankAmt5: 611,
    daibumonNam: '',
    kizaiQty: 0,
    mem: '',
    bumonNam: '',
    shukeibumonNam: '',
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 13,
    kizaiNam: 'SHARPY PLUS',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1012,
    rankAmt1: 1012,
    rankAmt2: 912,
    rankAmt3: 812,
    rankAmt4: 712,
    rankAmt5: 612,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 14,
    kizaiNam: 'ROBIN T5 Profile',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1013,
    rankAmt1: 1013,
    rankAmt2: 913,
    rankAmt3: 813,
    rankAmt4: 713,
    rankAmt5: 613,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 15,
    kizaiNam: 'ROBIN Pointe_Ω',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1014,
    rankAmt1: 1014,
    rankAmt2: 914,
    rankAmt3: 814,
    rankAmt4: 714,
    rankAmt5: 614,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 16,
    kizaiNam: 'MAC Ultra Wash',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1015,
    rankAmt1: 1015,
    rankAmt2: 915,
    rankAmt3: 815,
    rankAmt4: 715,
    rankAmt5: 615,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 17,
    kizaiNam: 'SHARPY PLUS',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1016,
    rankAmt1: 1016,
    rankAmt2: 916,
    rankAmt3: 816,
    rankAmt4: 716,
    rankAmt5: 616,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 18,
    kizaiNam: 'ROBIN T6 Profile',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1017,
    rankAmt1: 1017,
    rankAmt2: 917,
    rankAmt3: 817,
    rankAmt4: 717,
    rankAmt5: 617,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  {
    kizaiId: 19,
    kizaiNam: 'ROBIN Pointe_Ω',

    shozokuNam: '',
    mem: 'AAAAAAA',
    bumonNam: '',
    shukeibumonNam: '',
    regAmt: 1018,
    rankAmt1: 1018,
    rankAmt2: 918,
    rankAmt3: 818,
    rankAmt4: 718,
    rankAmt5: 618,
    daibumonNam: '',
    kizaiQty: 0,
    dspFlg: true,
    dspOrdNum: 0,
  },
  // {
  //   kizaiId: 20,
  //   kizaiNam: 'MAC Ultra Wash',
  //   delFlg: false,
  //    shozokuNam: ''7,
  //   bldCod: 'AA30',
  //   tanaCod: 'A30',
  //   edaCod: 'AA30',
  //   kizaiGrpCod: 'AA30',
  //   dspOrdNum: 20,
  //   mem: 'AAAAAAA',
  //   bumonNam: ''19,
  //   shukeibumonNam: ''19,
  //   dspFlg: true,
  //   ctnFlg: true,
  //   defDatQty: 19,
  //   regAmt: 1019,
  //   rankAmt1: 1019,
  //   rankAmt2: 919,
  //   rankAmt3: 819,
  //   rankAmt4: 719,
  //   rankAmt5: 619,
  //   sectionNum: 0,
  //   elNum: 0,
  //   addDat: new Date(),
  //   addUser: '',
  //   updDat: new Date(),
  //   updUser: '',
  // },
  // {
  //   kizaiId: 21,
  //   kizaiNam: 'SHARPY PLUS',
  //   delFlg: false,
  //    shozokuNam: ''8,
  //   bldCod: 'AA31',
  //   tanaCod: 'A31',
  //   edaCod: 'AA31',
  //   kizaiGrpCod: 'AA31',
  //   dspOrdNum: 21,
  //   mem: 'AAAAAAA',
  //   bumonNam: ''20,
  //   shukeibumonNam: ''20,
  //   dspFlg: true,
  //   ctnFlg: true,
  //   defDatQty: 20,
  //   regAmt: 1020,
  //   rankAmt1: 1020,
  //   rankAmt2: 920,
  //   rankAmt3: 820,
  //   rankAmt4: 720,
  //   rankAmt5: 620,
  //   sectionNum: 0,
  //   elNum: 0,
  //   addDat: new Date(),
  //   addUser: '',
  //   updDat: new Date(),
  //   updUser: '',
  // },
  // {
  //   kizaiId: 22,
  //   kizaiNam: 'ROBIN T7 Profile',
  //   delFlg: false,
  //    shozokuNam: ''9,
  //   bldCod: 'AA32',
  //   tanaCod: 'A32',
  //   edaCod: 'AA32',
  //   kizaiGrpCod: 'AA32',
  //   dspOrdNum: 22,
  //   mem: 'AAAAAAA',
  //   bumonNam: ''21,
  //   shukeibumonNam: ''21,
  //   dspFlg: true,
  //   ctnFlg: true,
  //   defDatQty: 21,
  //   regAmt: 1021,
  //   rankAmt1: 1021,
  //   rankAmt2: 921,
  //   rankAmt3: 821,
  //   rankAmt4: 721,
  //   rankAmt5: 621,
  //   sectionNum: 0,
  //   elNum: 0,
  //   addDat: new Date(),
  //   addUser: '',
  //   updDat: new Date(),
  //   updUser: '',
  // },
  // {
  //   kizaiId: 23,
  //   kizaiNam: 'ROBIN Pointe_Ω',
  //   delFlg: false,
  //    shozokuNam: ''10,
  //   bldCod: 'AA33',
  //   tanaCod: 'A33',
  //   edaCod: 'AA33',
  //   kizaiGrpCod: 'AA33',
  //   dspOrdNum: 23,
  //   mem: 'AAAAAAA',
  //   bumonNam: ''22,
  //   shukeibumonNam: ''22,
  //   dspFlg: true,
  //   ctnFlg: true,
  //   defDatQty: 22,
  //   regAmt: 1022,
  //   rankAmt1: 1022,
  //   rankAmt2: 922,
  //   rankAmt3: 822,
  //   rankAmt4: 722,
  //   rankAmt5: 622,
  //   sectionNum: 0,
  //   elNum: 0,
  //   addDat: new Date(),
  //   addUser: '',
  //   updDat: new Date(),
  //   updUser: '',
  // },
  // {
  //   kizaiId: 24,
  //   kizaiNam: 'MAC Ultra Wash',
  //   delFlg: false,
  //    shozokuNam: ''11,
  //   bldCod: 'AA34',
  //   tanaCod: 'A34',
  //   edaCod: 'AA34',
  //   kizaiGrpCod: 'AA34',
  //   dspOrdNum: 24,
  //   mem: 'AAAAAAA',
  //   bumonNam: ''23,
  //   shukeibumonNam: ''23,
  //   dspFlg: true,
  //   ctnFlg: true,
  //   defDatQty: 23,
  //   regAmt: 1023,
  //   rankAmt1: 1023,
  //   rankAmt2: 923,
  //   rankAmt3: 823,
  //   rankAmt4: 723,
  //   rankAmt5: 623,
  //   sectionNum: 0,
  //   elNum: 0,
  //   addDat: new Date(),
  //   addUser: '',
  //   updDat: new Date(),
  //   updUser: '',
  // },
  // {
  //   kizaiId: 25,
  //   kizaiNam: 'SHARPY PLUS',
  //   delFlg: false,
  //    shozokuNam: ''12,
  //   bldCod: 'AA35',
  //   tanaCod: 'A35',
  //   edaCod: 'AA35',
  //   kizaiGrpCod: 'AA35',
  //   dspOrdNum: 25,
  //   mem: 'AAAAAAA',
  //   bumonNam: ''24,
  //   shukeibumonNam: ''24,
  //   dspFlg: true,
  //   ctnFlg: true,
  //   defDatQty: 24,
  //   regAmt: 1024,
  //   rankAmt1: 1024,
  //   rankAmt2: 924,
  //   rankAmt3: 824,
  //   rankAmt4: 724,
  //   rankAmt5: 624,
  //   sectionNum: 0,
  //   elNum: 0,
  //   addDat: new Date(),
  //   addUser: '',
  //   updDat: new Date(),
  //   updUser: '',
  // },
  // {
  //   kizaiId: 26,
  //   kizaiNam: 'ROBIN T8 Profile',
  //   delFlg: false,
  //    shozokuNam: ''13,
  //   bldCod: 'AA36',
  //   tanaCod: 'A36',
  //   edaCod: 'AA36',
  //   kizaiGrpCod: 'AA36',
  //   dspOrdNum: 26,
  //   mem: 'AAAAAAA',
  //   bumonNam: ''25,
  //   shukeibumonNam: ''25,
  //   dspFlg: true,
  //   ctnFlg: true,
  //   defDatQty: 25,
  //   regAmt: 1025,
  //   rankAmt1: 1025,
  //   rankAmt2: 925,
  //   rankAmt3: 825,
  //   rankAmt4: 725,
  //   rankAmt5: 625,
  //   sectionNum: 0,
  //   elNum: 0,
  //   addDat: new Date(),
  //   addUser: '',
  //   updDat: new Date(),
  //   updUser: '',
  // },
  // {
  //   kizaiId: 27,
  //   kizaiNam: 'ROBIN Pointe_Ω',
  //   delFlg: false,
  //    shozokuNam: ''1,
  //   bldCod: 'AA37',
  //   tanaCod: 'A37',
  //   edaCod: 'AA37',
  //   kizaiGrpCod: 'AA37',
  //   dspOrdNum: 27,
  //   mem: 'AAAAAAA',
  //   bumonNam: ''26,
  //   shukeibumonNam: ''26,
  //   dspFlg: true,
  //   ctnFlg: true,
  //   defDatQty: 26,
  //   regAmt: 1026,
  //   rankAmt1: 1026,
  //   rankAmt2: 926,
  //   rankAmt3: 826,
  //   rankAmt4: 726,
  //   rankAmt5: 626,
  //   sectionNum: 0,
  //   elNum: 0,
  //   addDat: new Date(),
  //   addUser: '',
  //   updDat: new Date(),
  //   updUser: '',
  // },
  // {
  //   kizaiId: 28,
  //   kizaiNam: 'MAC Ultra Wash',
  //   delFlg: false,
  //    shozokuNam: ''2,
  //   bldCod: 'AA38',
  //   tanaCod: 'A38',
  //   edaCod: 'AA38',
  //   kizaiGrpCod: 'AA38',
  //   dspOrdNum: 28,
  //   mem: 'AAAAAAA',
  //   bumonNam: ''27,
  //   shukeibumonNam: ''27,
  //   dspFlg: true,
  //   ctnFlg: true,
  //   defDatQty: 27,
  //   regAmt: 1027,
  //   rankAmt1: 1027,
  //   rankAmt2: 927,
  //   rankAmt3: 827,
  //   rankAmt4: 727,
  //   rankAmt5: 627,
  //   sectionNum: 0,
  //   elNum: 0,
  //   addDat: new Date(),
  //   addUser: '',
  //   updDat: new Date(),
  //   updUser: '',
  // },
  // {
  //   kizaiId: 29,
  //   kizaiNam: 'SHARPY PLUS',
  //   delFlg: false,
  //    shozokuNam: ''3,
  //   bldCod: 'AA39',
  //   tanaCod: 'A39',
  //   edaCod: 'AA39',
  //   kizaiGrpCod: 'AA39',
  //   dspOrdNum: 29,
  //   mem: 'AAAAAAA',
  //   bumonNam: ''28,
  //   shukeibumonNam: ''28,
  //   dspFlg: true,
  //   ctnFlg: true,
  //   defDatQty: 28,
  //   regAmt: 1028,
  //   rankAmt1: 1028,
  //   rankAmt2: 928,
  //   rankAmt3: 828,
  //   rankAmt4: 728,
  //   rankAmt5: 628,
  //   sectionNum: 0,
  //   elNum: 0,
  //   addDat: new Date(),
  //   addUser: '',
  //   updDat: new Date(),
  //   updUser: '',
  // },
  // {
  //   kizaiId: 30,
  //   kizaiNam: 'ROBIN T9 Profile',
  //   delFlg: false,
  //    shozokuNam: ''4,
  //   bldCod: 'AA40',
  //   tanaCod: 'A40',
  //   edaCod: 'AA40',
  //   kizaiGrpCod: 'AA40',
  //   dspOrdNum: 30,
  //   mem: 'AAAAAAA',
  //   bumonNam: ''29,
  //   shukeibumonNam: ''29,
  //   dspFlg: true,
  //   ctnFlg: true,
  //   defDatQty: 29,
  //   regAmt: 1029,
  //   rankAmt1: 1029,
  //   rankAmt2: 929,
  //   rankAmt3: 829,
  //   rankAmt4: 729,
  //   rankAmt5: 629,
  //   sectionNum: 0,
  //   elNum: 0,
  //   addDat: new Date(),
  //   addUser: '',
  //   updDat: new Date(),
  //   updUser: '',
  // },

  /* {
      id: 21,
      name: 'SHARPY PLUS',
      quantity: 0,
      bumon: '',
      daiBumon: '',
      shuukeibumon: '',
      isshiki: '',
      serialnumber: 0,
      price1: 0,
      price2: 0,
      price3: 0,
      price4: 0,
      price5: 0,
      memo: '',
    },
    {
      id: 22,
      name: 'ROBIN T2 Profile',
      quantity: 0,
      bumon: '',
      daiBumon: '',
      shuukeibumon: '',
      isshiki: '',
      serialnumber: 0,
      price1: 0,
      price2: 0,
      price3: 0,
      price4: 0,
      price5: 0,
      memo: '',
    },
    {
      id: 23,
      name: 'ROBIN Pointe_Ω',
      quantity: 0,
      bumon: '',
      daiBumon: '',
      shuukeibumon: '',
      isshiki: '',
      serialnumber: 0,
      price1: 0,
      price2: 0,
      price3: 0,
      price4: 0,
      price5: 0,
      memo: '',
    },
    {
      id: 24,
      name: 'MAC Ultra Wash',
      quantity: 0,
      bumon: '',
      daiBumon: '',
      shuukeibumon: '',
      isshiki: '',
      serialnumber: 0,
      price1: 0,
      price2: 0,
      price3: 0,
      price4: 0,
      price5: 0,
      memo: '',
    },
    {
      id: 25,
      name: 'B',
      quantity: 0,
      bumon: '',
      daiBumon: '',
      shuukeibumon: '',
      isshiki: '',
      serialnumber: 0,
      price1: 0,
      price2: 0,
      price3: 0,
      price4: 0,
      price5: 0,
      memo: '',
    } /**
    { id: 26, name: 'C', cateId: 7, setId: 'a' },
    { id: 27, name: 'D', cateId: 8, setId: 'a' },
    { id: 28, name: 'A', cateId: 9, setId: 'a' },
    { id: 29, name: 'B', cateId: 10, setId: 'a' },
    { id: 30, name: 'C', cateId: 11, setId: '' },
    { id: 31, name: 'D', cateId: 12, setId: 'a' },
    { id: 32, name: 'A', cateId: 13, setId: 'a' },
    { id: 33, name: 'B', cateId: 15, setId: 'a' },
    { id: 34, name: 'C', cateId: 16, setId: 'a' },
    { id: 35, name: 'D', cateId: 17, setId: '' },
    { id: 36, name: 'A', cateId: 1, setId: 'a' },
    { id: 37, name: 'B', cateId: 2, setId: 'a' },
    { id: 38, name: 'C', cateId: 3, setId: 'a' },
    { id: 39, name: 'D', cateId: 4, setId: 'a' },
    { id: 40, name: 'A', cateId: 5, setId: '' },
    { id: 41, name: 'B', cateId: 6, setId: 'a' },
    { id: 42, name: 'C', cateId: 7, setId: 'a' },
    { id: 43, name: 'A', cateId: 8, setId: 'a' },
    { id: 44, name: 'B', cateId: 9, setId: 'a' },
    { id: 45, name: 'C', cateId: 10, setId: 'a' },
    { id: 46, name: 'D', cateId: 11, setId: 'a' },
    { id: 47, name: 'A', cateId: 12, setId: 'a' },
    { id: 48, name: 'B', cateId: 13, setId: 'a' },
    { id: 49, name: 'C', cateId: 15, setId: 'a' },
    { id: 50, name: 'D', cateId: 16, setId: 'a' },
    { id: 51, name: 'A', cateId: 17, setId: 'a' },
    { id: 52, name: 'A', cateId: 0, setId: 'a' },
    { id: 53, name: 'B', cateId: 2, setId: 'a' },
    { id: 54, name: 'C', cateId: 3, setId: 'a' },
    { id: 55, name: 'D', cateId: 4, setId: 'a' },
    { id: 56, name: 'A', cateId: 5, setId: 'a' },
    { id: 57, name: 'A', cateId: 6, setId: 'a' },
    { id: 58, name: 'B', cateId: 0, setId: 'a' },
    { id: 59, name: 'C', cateId: 8, setId: 'a' },
    { id: 60, name: 'D', cateId: 9, setId: 'a' },
    { id: 61, name: 'A', cateId: 10, setId: 'a' },
    { id: 62, name: 'A', cateId: 11, setId: 'a' },
    { id: 63, name: 'B', cateId: 12, setId: 'a' },
    { id: 64, name: 'C', cateId: 13, setId: 'a' },
    { id: 65, name: 'D', cateId: 15, setId: 'a' },
    { id: 66, name: 'A', cateId: 16, setId: 'a' },
    { id: 67, name: 'A', cateId: 17, setId: 'a' },
    { id: 68, name: 'B', cateId: 1, setId: 'a' },
    { id: 69, name: 'C', cateId: 0, setId: 'a' },
    { id: 70, name: 'D', cateId: 3, setId: 'a' },
    { id: 71, name: 'A', cateId: 4, setId: 'a' },
    { id: 72, name: 'A', cateId: 5, setId: 'a' },
    { id: 73, name: 'B', cateId: 6, setId: 'a' },
    { id: 74, name: 'C', cateId: 0, setId: 'a' },
    { id: 75, name: 'D', cateId: 8, setId: 'a' },
    { id: 76, name: 'A', cateId: 0, setId: 'a' },
    { id: 77, name: 'A', cateId: 10, setId: 'a' },
    { id: 78, name: 'B', cateId: 11, setId: 'a' },
    { id: 79, name: 'C', cateId: 0, setId: 'a' },
    { id: 80, name: 'D', cateId: 13, setId: 'a' }, */
];
