import { z } from 'zod';

export type EqptMasterData = {
  id: number;
  name: string;
  quantity: number;
  bumon: string;
  daiBumon: string;
  shuukeibumon: string;
  isshiki: string;
  serialnumber: number;
  price1: number;
  price2: number;
  price3: number;
  price4: number;
  price5: number;
  memo: string;
};

// 検索用zod
export const eqptMasterSchema = z.object({
  name: z.string(),
});
export type eqptMasterSearchData = z.infer<typeof eqptMasterSchema>;

/** 削除データ delete data */

export const eqptMasterList: EqptMasterData[] = [
  {
    id: 0,
    name: 'SHRPY X Spot',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 1,
    name: 'SHARPY PLUS',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 2,
    name: 'ROBIN T2 Profile',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 3,
    name: 'ROBIN Pointe_Ω',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 4,
    name: 'MAC Ultra Wash',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 5,
    name: 'SHRPY X Spot',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 6,
    name: 'SHARPY PLUS',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 7,
    name: 'ROBIN T2 Profile',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 8,
    name: 'ROBIN Pointe_Ω',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 9,
    name: 'MAC Ultra Wash',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 10,
    name: 'SHRPY X Spot',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 11,
    name: 'SHARPY PLUS',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 12,
    name: 'ROBIN T2 Profile',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 13,
    name: 'ROBIN Pointe_Ω',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 14,
    name: 'MAC Ultra Wash',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 15,
    name: 'SHRPY X Spot',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 16,
    name: 'SHARPY PLUS',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 17,
    name: 'ROBIN T2 Profile',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 18,
    name: 'ROBIN Pointe_Ω',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 19,
    name: 'MAC Ultra Wash',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 20,
    name: 'SHRPY X Spot',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 21,
    name: 'SHARPY PLUS',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 22,
    name: 'ROBIN T2 Profile',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 23,
    name: 'ROBIN Pointe_Ω',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 24,
    name: 'MAC Ultra Wash',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  },
  {
    id: 25,
    name: 'B',
    quantity: 0,
    bumon: '',
    daiBumon: '',
    shuukeibumon: '',
    isshiki: '',
    serialnumber: 0,
    price1: 0,
    price2: 0,
    price3: 0,
    price4: 0,
    price5: 0,
    memo: '',
  } /**
  { id: 26, name: 'C', cateId: 7, setId: 'a' },
  { id: 27, name: 'D', cateId: 8, setId: 'a' },
  { id: 28, name: 'A', cateId: 9, setId: 'a' },
  { id: 29, name: 'B', cateId: 10, setId: 'a' },
  { id: 30, name: 'C', cateId: 11, setId: '' },
  { id: 31, name: 'D', cateId: 12, setId: 'a' },
  { id: 32, name: 'A', cateId: 13, setId: 'a' },
  { id: 33, name: 'B', cateId: 15, setId: 'a' },
  { id: 34, name: 'C', cateId: 16, setId: 'a' },
  { id: 35, name: 'D', cateId: 17, setId: '' },
  { id: 36, name: 'A', cateId: 1, setId: 'a' },
  { id: 37, name: 'B', cateId: 2, setId: 'a' },
  { id: 38, name: 'C', cateId: 3, setId: 'a' },
  { id: 39, name: 'D', cateId: 4, setId: 'a' },
  { id: 40, name: 'A', cateId: 5, setId: '' },
  { id: 41, name: 'B', cateId: 6, setId: 'a' },
  { id: 42, name: 'C', cateId: 7, setId: 'a' },
  { id: 43, name: 'A', cateId: 8, setId: 'a' },
  { id: 44, name: 'B', cateId: 9, setId: 'a' },
  { id: 45, name: 'C', cateId: 10, setId: 'a' },
  { id: 46, name: 'D', cateId: 11, setId: 'a' },
  { id: 47, name: 'A', cateId: 12, setId: 'a' },
  { id: 48, name: 'B', cateId: 13, setId: 'a' },
  { id: 49, name: 'C', cateId: 15, setId: 'a' },
  { id: 50, name: 'D', cateId: 16, setId: 'a' },
  { id: 51, name: 'A', cateId: 17, setId: 'a' },
  { id: 52, name: 'A', cateId: 0, setId: 'a' },
  { id: 53, name: 'B', cateId: 2, setId: 'a' },
  { id: 54, name: 'C', cateId: 3, setId: 'a' },
  { id: 55, name: 'D', cateId: 4, setId: 'a' },
  { id: 56, name: 'A', cateId: 5, setId: 'a' },
  { id: 57, name: 'A', cateId: 6, setId: 'a' },
  { id: 58, name: 'B', cateId: 0, setId: 'a' },
  { id: 59, name: 'C', cateId: 8, setId: 'a' },
  { id: 60, name: 'D', cateId: 9, setId: 'a' },
  { id: 61, name: 'A', cateId: 10, setId: 'a' },
  { id: 62, name: 'A', cateId: 11, setId: 'a' },
  { id: 63, name: 'B', cateId: 12, setId: 'a' },
  { id: 64, name: 'C', cateId: 13, setId: 'a' },
  { id: 65, name: 'D', cateId: 15, setId: 'a' },
  { id: 66, name: 'A', cateId: 16, setId: 'a' },
  { id: 67, name: 'A', cateId: 17, setId: 'a' },
  { id: 68, name: 'B', cateId: 1, setId: 'a' },
  { id: 69, name: 'C', cateId: 0, setId: 'a' },
  { id: 70, name: 'D', cateId: 3, setId: 'a' },
  { id: 71, name: 'A', cateId: 4, setId: 'a' },
  { id: 72, name: 'A', cateId: 5, setId: 'a' },
  { id: 73, name: 'B', cateId: 6, setId: 'a' },
  { id: 74, name: 'C', cateId: 0, setId: 'a' },
  { id: 75, name: 'D', cateId: 8, setId: 'a' },
  { id: 76, name: 'A', cateId: 0, setId: 'a' },
  { id: 77, name: 'A', cateId: 10, setId: 'a' },
  { id: 78, name: 'B', cateId: 11, setId: 'a' },
  { id: 79, name: 'C', cateId: 0, setId: 'a' },
  { id: 80, name: 'D', cateId: 13, setId: 'a' }, */,
];
