const equipmentHeaders = [
  { key: 'name', label: '機材明細名' },
  { key: 'status', label: 'ステータス' },
  { key: 'issue', label: '出庫' },
  { key: 'return', label: '入庫' },
  { key: 'preparation', label: '仕込' },
  { key: 'rh', label: 'RH' },
  { key: 'gp', label: 'GP' },
  { key: 'actual', label: '本番' },
  { key: 'keep', label: 'キープ' },
  { key: 'days', label: '日数' },
  { key: 'price', label: '小計価格' },
  { key: 'tax', label: '税' },
  { key: 'caveat', label: '警告' },
];

const vehicleHeaders = [
  { key: 'name', label: '車両明細名' },
  { key: 'classification', label: '区分' },
  { key: 'days', label: ' 日付' },
  { key: 'memo', label: '車両メモ' },
];
const equipmentRows = [
  {
    id: 1,
    name: '埼玉アリーナ1102',
    status: '出庫チェック済み',
    issue: '2025/11/02 10:00',
    return: '2025/11/09 15:00',
    preparation: 2,
    rh: 3,
    gp: 3,
    actual: 3,
    keep: 4,
    days: 3,
    price: 2400000,
    tax: '外税',
    caveat: '',
  },
  {
    id: 2,
    name: '埼玉アリーナ1104',
    status: '未作業',
    issue: '2025/11/04 10:00',
    return: '2025/11/09 15:00',
    preparation: 2,
    rh: 3,
    gp: 3,
    actual: 2,
    keep: 4,
    days: 2,
    price: 2100000,
    tax: '外税',
    caveat: '',
  },
  {
    id: 3,
    name: '横浜アリーナ1204',
    status: '未作業',
    issue: '2025/11/13 10:00',
    return: '2025/11/20 15:00',
    preparation: 2,
    rh: 3,
    gp: 3,
    actual: 4,
    keep: 0,
    days: 4,
    price: 3400000,
    tax: '外税',
    caveat: '',
  },
];

const vehicleRows = [
  {
    id: 1,
    name: '埼玉アリーナ積み',
    classification: '出庫',
    days: '2025/11/02 10:00',
    memo: 'XXX',
  },
  {
    id: 2,
    name: '埼玉アリーナ積み',
    classification: '出庫',
    days: '2025/11/04 10:00',
    memo: 'XXX',
  },
  {
    id: 3,
    name: '埼玉アリーナ降ろし',
    classification: '入庫',
    days: '2025/11/09 15:00',
    memo: 'XXX',
  },
  {
    id: 4,
    name: '横浜アリーナ積み',
    classification: '出庫',
    days: '2025/11/13 10:00',
    memo: 'XXX',
  },
  {
    id: 5,
    name: '横浜アリーナ降ろし',
    classification: '入庫',
    days: '2025/11/20 15:00',
    memo: 'XXX',
  },
];

export { equipmentHeaders, equipmentRows, vehicleHeaders, vehicleRows };
