const equipmentHeaders = [
  { key: 'name', label: '機材明細名' },
  { key: 'status', label: '作業ステータス' },
  { key: 'issue', label: '出庫' },
  { key: 'return', label: '入庫' },
  { key: 'preparation', label: '仕込' },
  { key: 'rh', label: 'RH' },
  { key: 'gp', label: 'GP' },
  { key: 'actual', label: '本番' },
  { key: 'days', label: '日数' },
  { key: 'price', label: '小計金額' },
  { key: 'caveat', label: '警告' },
];

const vehicleHeaders = [
  { key: 'name', label: '車両明細名' },
  { key: 'classification', label: '区分' },
  { key: 'days', label: ' 日付' },
  { key: 'memo', label: '車両メモ' },
];
const equipmentRows = [
  {
    id: 1,
    name: 'Zepp Tourメイン',
    status: '出庫済み',
    issue: '2025/11/02 10:00',
    return: '2025/11/20 15:00',
    preparation: 4,
    rh: 4,
    gp: 4,
    actual: 3,
    days: 6,
    price: 4800000,
    caveat: '',
  },
  {
    id: 2,
    name: 'カット（YARD/HT）',
    status: '入庫済み',
    issue: '',
    return: '2025/11/02 15:00',
    preparation: '',
    rh: '',
    gp: '',
    actual: '',
    days: 2,
    price: -400000,
    caveat: '',
  },
  {
    id: 3,
    name: 'キープ分（YARD/HT）',
    status: '出庫済み',
    issue: '2025/11/13 10:00',
    return: '2025/11/09 15:00',
    preparation: '',
    rh: '',
    gp: '',
    actual: '',
    days: '',
    price: undefined,
    caveat: '',
  },
  {
    id: 4,
    name: 'キープ機材から一部返却',
    status: '入庫済み',
    issue: '',
    return: '2025/11/04 15:00',
    preparation: '',
    rh: '',
    gp: '',
    actual: '',
    days: '',
    price: undefined,
    caveat: '',
  },
  {
    id: 5,
    name: 'キープ機材に戻し',
    status: '出庫済み',
    issue: '2025/11/05 10:00',
    return: '',
    preparation: '',
    rh: '',
    gp: '',
    actual: '',
    days: '',
    price: undefined,
    caveat: '',
  },
  {
    id: 6,
    name: '追加分',
    status: '出庫済み',
    issue: '2025/11/05 10:00',
    return: '2025/11/20 15:00',
    preparation: '',
    rh: '',
    gp: '',
    actual: '',
    days: 4,
    price: 200000,
    caveat: '',
  },
  {
    id: 7,
    name: 'キープ分（YARD/HT）',
    status: '出庫スタンバイ済み',
    issue: '2025/11/13 10:00',
    return: '2025/11/09 15:00',
    preparation: '',
    rh: '',
    gp: '',
    actual: '',
    days: '',
    price: undefined,
    caveat: '',
  },
  {
    id: 8,
    name: '横浜アリーナ（追加分）',
    status: '出庫スタンバイ済み',
    issue: '2025/11/13 10:00',
    return: '2025/11/20 15:00',
    preparation: '',
    rh: '',
    gp: '',
    actual: '',
    days: '',
    price: undefined,
    caveat: '',
  },
];

const vehicleRows = [
  {
    id: 1,
    name: '埼玉アリーナ積み',
    classification: '出庫',
    days: '2025/11/02 10:00',
    memo: 'XXX',
  },
  {
    id: 2,
    name: '埼玉アリーナ積み',
    classification: '出庫',
    days: '2025/11/04 10:00',
    memo: 'XXX',
  },
  {
    id: 3,
    name: '埼玉アリーナ降ろし',
    classification: '入庫',
    days: '2025/11/09 15:00',
    memo: 'XXX',
  },
  {
    id: 4,
    name: '横浜アリーナ積み',
    classification: '出庫',
    days: '2025/11/13 10:00',
    memo: 'XXX',
  },
  {
    id: 5,
    name: '横浜アリーナ降ろし',
    classification: '入庫',
    days: '2025/11/20 15:00',
    memo: 'XXX',
  },
];

export { equipmentHeaders, equipmentRows, vehicleHeaders, vehicleRows };
