const equipmentHeaders = [
  { key: 'name', label: '名称' },
  { key: 'status', label: 'ステータス' },
  { key: 'issue', label: '出庫' },
  { key: 'return', label: '入庫' },
  { key: 'preparation', label: '仕込' },
  { key: 'rh', label: 'RH' },
  { key: 'gp', label: 'GP' },
  { key: 'actual', label: '本番' },
  { key: 'unitprice', label: '単価' },
  { key: 'quantity', label: '数量' },
  { key: 'spare', label: '予備数' },
  { key: 'days', label: '日数' },
  { key: 'price', label: '価格' },
  { key: 'tax', label: '税' },
  { key: 'caveat', label: '警告' },
  { key: 'memo', label: '機材メモ' },
];

const vehicleHeaders = [
  { key: 'classification', label: '区分' },
  { key: 'days', label: ' 日付' },
  { key: 'name', label: '名称' },
  { key: 'work', label: '作業' },
  { key: 'memo', label: '車両メモ' },
];
const equipmentRows = [
  {
    id: 1,
    name: 'SHARPY',
    status: '準備中',
    issue: '2025/11/2 KICKS',
    return: '2025/11/4 KICKS',
    preparation: '2025/11/2',
    rh: '2025/11/2',
    gp: '2025/11/2',
    actual: '2025/11/3',
    unitprice: 12000,
    quantity: 2,
    spare: 1,
    days: 3,
    price: 72000,
    tax: '外税',
    caveat: 'マイナス在庫',
    memo: 'XXX',
  },
  {
    id: 2,
    name: 'SHARPY',
    status: '準備中',
    issue: '2025/11/2 KICKS',
    return: '2025/11/4 KICKS',
    preparation: '2025/11/2',
    rh: '2025/11/2',
    gp: '2025/11/2',
    actual: '2025/11/3',
    unitprice: 25000,
    quantity: 3,
    spare: 1,
    days: 4,
    price: 300000,
    tax: '外税',
    caveat: '',
    memo: 'XXX',
  },
  {
    id: 3,
    name: 'SHARPY',
    status: '準備中',
    issue: '2025/11/2 KICKS',
    return: '2025/11/4 KICKS',
    preparation: '2025/11/2',
    rh: '2025/11/2',
    gp: '2025/11/2',
    actual: '2025/11/3',
    unitprice: 12000,
    quantity: 2,
    spare: 1,
    days: 3,
    price: 72000,
    tax: '外税',
    caveat: '',
    memo: 'XXX',
  },
  {
    id: 4,
    name: 'SHARPY',
    status: '準備中',
    issue: '2025/11/2 KICKS',
    return: '2025/11/4 KICKS',
    preparation: '2025/11/2',
    rh: '2025/11/2',
    gp: '2025/11/2',
    actual: '2025/11/3',
    unitprice: 12000,
    quantity: 2,
    spare: 1,
    days: 3,
    price: 72000,
    tax: '外税',
    caveat: '',
    memo: 'XXX',
  },
  {
    id: 5,
    name: 'SHARPY',
    status: '準備中',
    issue: '2025/11/2 KICKS',
    return: '2025/11/4 KICKS',
    preparation: '2025/11/2',
    rh: '2025/11/2',
    gp: '2025/11/2',
    actual: '2025/11/3',
    unitprice: 12000,
    quantity: 2,
    spare: 1,
    days: 3,
    price: 72000,
    tax: '外税',
    caveat: '',
    memo: 'XXX',
  },
];

const vehicleRows = [
  {
    id: 1,
    classification: '出庫',
    days: '2025/11/2',
    name: 'ハイエース',
    work: 'KICK',
    memo: 'XXX',
  },
  {
    id: 2,
    classification: '出庫',
    days: '2025/11/2',
    name: 'ハイエース',
    work: 'KICK',
    memo: 'XXX',
  },
  {
    id: 3,
    classification: '入庫',
    days: '2025/11/2',
    name: 'ハイエース',
    work: 'KICK',
    memo: 'XXX',
  },
  {
    id: 4,
    classification: '入庫',
    days: '2025/11/2',
    name: '11t',
    work: 'YARD',
    memo: 'XXX',
  },
  {
    id: 5,
    classification: '入庫',
    days: '2025/11/2',
    name: '11t',
    work: 'YARD',
    memo: 'XXX',
  },
];

export { equipmentHeaders, equipmentRows, vehicleHeaders, vehicleRows };
