import { Row } from '../_ui/order-table';

const equipmentHeaders = [
  { key: 'name', label: '受注明細名' },
  { key: 'status', label: '作業ステータス' },
  { key: 'issue', label: '出庫' },
  { key: 'return', label: '入庫' },
  { key: 'preparation', label: '仕込' },
  { key: 'rh', label: 'RH' },
  { key: 'gp', label: 'GP' },
  { key: 'actual', label: '本番' },
  { key: 'days', label: '日数' },
  { key: 'price', label: '小計金額' },
  { key: 'caveat', label: '警告' },
];

const vehicleHeaders = [
  { key: 'name', label: '車両明細名' },
  { key: 'classification', label: '区分' },
  { key: 'days', label: ' 日付' },
  { key: 'memo', label: '車両メモ' },
];

const equipmentRows: Row[] = [
  {
    id: 1,
    name: 'メイン機材',
    status: '出庫済み',
    issue: '2025/11/02 10:00',
    return: '2025/11/20 15:00',
    preparation: 4,
    rh: 4,
    gp: 4,
    actual: 3,
    days: 6,
    price: 4800000,
    caveat: '',
    juchuKizaiHeadKbn: 1,
  },
  {
    id: 2,
    name: 'カット（YARD/HT）',
    status: '入庫済み',
    issue: '',
    return: '2025/11/02 15:00',
    preparation: undefined,
    rh: undefined,
    gp: undefined,
    actual: undefined,
    days: 2,
    price: -400000,
    caveat: '',
    juchuKizaiHeadKbn: 2,
  },
  {
    id: 3,
    name: 'キープ分（YARD/HT）',
    status: '出庫済み',
    issue: '2025/11/13 10:00',
    return: '2025/11/09 15:00',
    preparation: undefined,
    rh: undefined,
    gp: undefined,
    actual: undefined,
    days: undefined,
    price: undefined,
    caveat: '',
    juchuKizaiHeadKbn: 3,
  },
  {
    id: 4,
    name: 'キープ分（YARD/HT）',
    status: '出庫済み',
    issue: '2025/11/14 10:00',
    return: '2025/11/09 15:00',
    preparation: undefined,
    rh: undefined,
    gp: undefined,
    actual: undefined,
    days: undefined,
    price: undefined,
    caveat: '',
    juchuKizaiHeadKbn: 3,
  },
  {
    id: 5,
    name: 'キープ機材から一部返却',
    status: '入庫済み',
    issue: '',
    return: '2025/11/04 15:00',
    preparation: undefined,
    rh: undefined,
    gp: undefined,
    actual: undefined,
    days: undefined,
    price: undefined,
    caveat: '',
    juchuKizaiHeadKbn: 2,
  },
  {
    id: 6,
    name: 'キープ機材から一部返却（再出庫）',
    status: '出庫済み',
    issue: '',
    return: '2025/11/05 15:00',
    preparation: undefined,
    rh: undefined,
    gp: undefined,
    actual: undefined,
    days: undefined,
    price: undefined,
    caveat: '',
    juchuKizaiHeadKbn: 1,
  },
  {
    id: 7,
    name: '追加分',
    status: '出庫済み',
    issue: '2025/11/05 10:00',
    return: '2025/11/20 15:00',
    preparation: undefined,
    rh: undefined,
    gp: undefined,
    actual: undefined,
    days: 4,
    price: 200000,
    caveat: '',
    juchuKizaiHeadKbn: 1,
  },
  {
    id: 8,
    name: 'キープ分（YARD/HT）',
    status: '出庫スタンバイ済み',
    issue: '2025/11/13 10:00',
    return: '2025/11/09 15:00',
    preparation: undefined,
    rh: undefined,
    gp: undefined,
    actual: undefined,
    days: undefined,
    price: undefined,
    caveat: '',
    juchuKizaiHeadKbn: 3,
  },
  {
    id: 9,
    name: '横浜アリーナ（追加分）',
    status: '出庫スタンバイ済み',
    issue: '2025/11/13 10:00',
    return: '2025/11/20 15:00',
    preparation: undefined,
    rh: undefined,
    gp: undefined,
    actual: undefined,
    days: undefined,
    price: undefined,
    caveat: '',
    juchuKizaiHeadKbn: 1,
  },
];

const vehicleRows = [
  {
    juchuHeadId: 1,
    juchuSharyoHeadId: 1,
    headNam: '埼玉アリーナ積み',
    kbn: '出庫',
    dat: new Date('2025/11/02 10:00'),
    mem: 'XXX',
  },
  {
    juchuHeadId: 1,
    juchuSharyoHeadId: 2,
    headNam: '埼玉アリーナ積み',
    kbn: '出庫',
    dat: new Date('2025/11/04 10:00'),
    mem: 'XXX',
  },
  {
    juchuHeadId: 1,
    juchuSharyoHeadId: 3,
    headNam: '埼玉アリーナ降ろし',
    kbn: '入庫',
    dat: new Date('2025/11/09 15:00'),
    mem: 'XXX',
  },
  {
    juchuHeadId: 1,
    juchuSharyoHeadId: 4,
    headNam: '横浜アリーナ積み',
    kbn: '出庫',
    dat: new Date('2025/11/13 10:00'),
    mem: 'XXX',
  },
  {
    juchuHeadId: 1,
    juchuSharyoHeadId: 5,
    headNam: '横浜アリーナ降ろし',
    kbn: '入庫',
    dat: new Date('2025/11/20 15:00'),
    mem: 'XXX',
  },
];

const users = [
  {
    id: 1,
    name: '鈴木　一郎',
  },
  {
    id: 2,
    name: '鈴木　二郎',
  },
  {
    id: 3,
    name: '鈴木　三郎',
  },
  {
    id: 4,
    name: '鈴木　四郎',
  },
  {
    id: 5,
    name: '鈴木　五郎',
  },
  {
    id: 6,
    name: '鈴木　六郎',
  },
  {
    id: 7,
    name: '鈴木　七郎',
  },
  {
    id: 8,
    name: '鈴木　八郎',
  },
  {
    id: 9,
    name: '鈴木　九郎',
  },
  {
    id: 10,
    name: 'test_user',
  },
  {
    id: 11,
    name: '米山Y',
  },
  {
    id: 12,
    name: '柏井S',
  },
];

export { equipmentHeaders, equipmentRows, users, vehicleHeaders, vehicleRows };
